[build]
command = "npx next build"
publish = ".next"

[[redirects]]
from = "http://www.ontheflywastesolutions.com/*"
to = "https://ontheflywastesolutions.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://ontheflywastesolutions.com/*"
to = "https://ontheflywastesolutions.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.ontheflywastesolutions.com/*"
to = "https://ontheflywastesolutions.com/:splat"
status = 301
force = true

[[plugins]]
package = "@netlify/plugin-nextjs"
